export const OPENX_OPENAI_IMAGE_PROVIDER_KEY = 'openx-openai-image';
export const OPENX_OPENAI_IMAGE_DEFAULT_MODEL = 'gpt-image-2';
export const OPENX_OPENAI_IMAGE_DEFAULT_REF = `${OPENX_OPENAI_IMAGE_PROVIDER_KEY}/${OPENX_OPENAI_IMAGE_DEFAULT_MODEL}`;
